name: gateway
description: gateway
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # https://pub.dev/packages/dio
  dio: ^4.0.0
  # fonts https://pub.dev/packages/json_annotation
  json_annotation: ^4.3.0
  # fonts https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^1.0.0

  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^1.0.0
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^7.3.3
  # https://pub.dev/packages/build_runner
  build_runner: ^2.0.4
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.0.1
  # https://pub.dev/packages/analyzer
  analyzer: ^2.3.0

  # https://pub.dev/packages/data_connection_checker
  data_connection_checker:
    git:
      url: https://github.com/Winreer324/data_connection_checker.git
      ref: feature/null_safety

  # https://pub.dev/packages/mockito
  mockito: ^5.0.16

  # https://pub.dev/packages/freezed
  freezed: ^1.0.0

flutter:
